### ISSUE TITLE
'Passing score' takes non-integer chaacters, resulting in RedScreen on access.

### ISSUE THREAD

**Issue by fuchsi3010** [OpenOLAT/OpenOLAT#100]
in a classic course, if an 'assessment' course element and another element exists, the access for the other course element can be restricted 'Depending on assessment' --> 'Check score'.

the field for 'Passing score' is '0' by default, but non-integer characters can be input (tested: "jklk").
after saving and publishing, the course element will become unavailable, for both accessing and editing (!), both resulting in a RedScreen.
![Screenshot from 2023-10-30 15-18-32](https://github.com/OpenOLAT/OpenOLAT/assets/37498115/debdbc9f-738b-4efc-96e5-0c0237549f36)
(sry for mixed english and german!)

in our case, if an (system) administrator visits a misconfigured course element of a user, we cannot access or edit the course element:
![Screenshot from 2023-10-30 15-25-13](https://github.com/OpenOLAT/OpenOLAT/assets/37498115/ea739ac1-71a9-4e6d-97e1-eb23a64f4ffe)

is there any way to save the user's course? do we need to edit a database entry directly (which one?) or is there an API call?
thanks!

Edit: We run a modified version of 17.2.16, but i just set up a the latest frentix version (18.1.0) and could reproduce the issue there. both instances with postgres 12

**Comment by lainsr** [comment]
Thank you for the report. I open an issue for it:

https://jira.openolat.org/browse/OO-7383

**Comment by fuchsi3010** [comment]
thank you!

i just noticed i didn't provide a stacktrace, sry!
this is in 18.1.0:
```
2023-10-31 11:32:26.410 [http-nio-8088-exec-5] ERROR  ExceptionWindowController ^%^ I90-J176 ^%^ org.olat.core.gui.exception.ExceptionWindowController ^%^ 360448 ^%^ (REDACTED) ^%^ http://localhost:8088/auth/RepositoryEntry/786432/Editor/0 ^%^ Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0 ^%^ **RedScreen** For input string: "jhkasld" ::_::<dispatchinfo>  <componentinfo>   <compname>luTree</compname>   <compclass>org.olat.core.gui.components.tree.MenuTree</compclass>   <extendedinfo>n/a</extendedinfo>   <event>    <class>org.olat.core.gui.components.tree.TreeEvent</class>    <command>ctncl</command>    <tostring>TreeEvent:{cmd:ctncl, nodeid:108719860155472}</tostring>   </event>  </componentinfo>  <controllerinfo>   <controllername>org.olat.course.editor.EditorMainController</controllername>   <controllername>org.olat.course.run.CourseRuntimeController</controllername>   <controllername>org.olat.core.commons.fullWebApp.BaseFullWebappController</controllername>  </controllerinfo> </dispatchinfo> ::_:: java.lang.NumberFormatException: For input string: "jhkasld"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:668)
at java.base/java.lang.Integer.valueOf(Integer.java:999)
at org.olat.course.condition.ConditionConfigEasyController.initAssessmentSwitch(ConditionConfigEasyController.java:410)
at org.olat.course.condition.ConditionConfigEasyController.initForm(ConditionConfigEasyController.java:195)
at org.olat.core.gui.components.form.flexible.impl.FormBasicController.initForm(FormBasicController.java:287)
at org.olat.course.condition.ConditionConfigEasyController.<init>(ConditionConfigEasyController.java:178)
at org.olat.course.condition.ConditionEditController.initEasyForm(ConditionEditController.java:153)
at org.olat.course.condition.ConditionEditController.doEasyMode(ConditionEditController.java:147)
at org.olat.course.condition.ConditionEditController.<init>(ConditionEditController.java:90)
at org.olat.course.editor.AccessEditController.<init>(AccessEditController.java:63)
at org.olat.course.condition.TabbableConditionNodeConfigController.<init>(TabbableConditionNodeConfigController.java:66)
at org.olat.course.condition.ConditionNodeAccessProvider.createEditController(ConditionNodeAccessProvider.java:109)
at org.olat.course.nodeaccess.manager.NodeAccessServiceImpl.createEditController(NodeAccessServiceImpl.java:124)
at org.olat.course.editor.NodeEditController.<init>(NodeEditController.java:148)
at org.olat.course.nodes.PageCourseNode.createEditController(PageCourseNode.java:130)
at org.olat.course.editor.EditorMainController.initNodeEditor(EditorMainController.java:629)
at org.olat.course.editor.EditorMainController.updateViewForSelectedNodeId(EditorMainController.java:606)
at org.olat.course.editor.EditorMainController.event(EditorMainController.java:469)
at org.olat.core.gui.control.DefaultController.dispatchEvent(DefaultController.java:216)
at org.olat.core.gui.components.AbstractComponent.lambda$fireEvent$0(AbstractComponent.java:262)
at org.olat.core.logging.activity.ThreadLocalUserActivityLoggerInstaller.runWithUserActivityLogger(ThreadLocalUserActivityLoggerInstaller.java:108)
at org.olat.core.gui.components.AbstractComponent.fireEvent(AbstractComponent.java:262)
at org.olat.core.gui.components.tree.MenuTree.handleClick(MenuTree.java:309)
at org.olat.core.gui.components.tree.MenuTree.doDispatchRequest(MenuTree.java:208)
at org.olat.core.gui.components.AbstractComponent.dispatchRequest(AbstractComponent.java:220)
at org.olat.core.gui.components.Window.doDispatchToComponent(Window.java:1284)
at org.olat.core.gui.components.Window.dispatchRequest(Window.java:454)
at org.olat.core.gui.components.Window.doDispatchRequest(Window.java:330)
at org.olat.core.gui.components.AbstractComponent.dispatchRequest(AbstractComponent.java:220)
at org.olat.dispatcher.AuthenticatedDispatcher.processValidDispatchURI(AuthenticatedDispatcher.java:289)
at org.olat.dispatcher.AuthenticatedDispatcher.execute(AuthenticatedDispatcher.java:194)
at org.olat.core.servlets.OpenOLATServlet.executeUserRequest(OpenOLATServlet.java:307)
at org.olat.core.servlets.OpenOLATServlet.doPost(OpenOLATServlet.java:235)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:563)
at org.olat.core.servlets.OpenOLATServlet.service(OpenOLATServlet.java:167)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:631)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.olat.core.servlets.HeadersFilter.doFilter(HeadersFilter.java:64)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:833)
```

also, the issue in our production system arose with an **empty string**, which i guess is the more likely scenario for a user, instead of inputting some random characters...

**Comment by lainsr** [comment]
Validation of the field come with OpenOlat 18.1.1
