### ISSUE TITLE
`Cannot read field "scale" because "multiplicand" is null` when editing Checklist Items in a Tally List

### ISSUE THREAD

**Issue by fuchsi3010** [OpenOLAT/OpenOLAT#103]
We have observed some users getting RedScreens when editing Checklist Items in a Tally List.
I could recreate the Issue in OpenOlat 18.2.0

### steps to reproduce
- Create a new course: Course design = classic, all else = defaults
- Course Editor -> Insert course elements -> Tally list
- Configuration -> Minimum score=0, Maximum score=2, Passed cut value=1
- Checkboxes -> Add Checkbox: Add 2 Checkboxes, Grant score on check=1
- Publish
- Exit Course Editor
- Switch to Participant View -> Check a Checkbox
- Switch to Owner View -> Course Editor -> Checkboxes
- Re-sort the checkboxes
- Publish -> Next -> Finish -> RedScreen -> Back -> Cancel
- Course Seems to be published
- If I change the order/resort the checkboxes -> Click on the Course Title -> Publish automatically -> No RedScreen

### Stacktraces

When Publishing manually:
```
2024-03-08 14:02:46.387 [ajp-nio2-127.0.0.1-8009-exec-3] ERROR  ExceptionWindowController ^%^ I42173-J76886 ^%^ org.olat.core.gui.exception.ExceptionWindowController ^%^ 5334106112 ^%^ 127.0.0.1 ^%^ https://localhost/auth/RepositoryEntry/5334466563/Editor/0 ^%^ Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0 ^%^ **RedScreen** Cannot read field "scale" because "multiplicand" is null ::_::<dispatchinfo>  <componentinfo>   <compname>ffo_main_stepslayout</compname>   <compclass>org.olat.core.gui.components.form.flexible.impl.FormWrapperContainer</compclass>   <extendedinfo>n/a</extendedinfo>   <event>    <class>org.olat.core.gui.control.Event</class>    <command>validation finish</command>    <tostring>com:validation finish,org.olat.core.gui.control.Event@2f96e239</tostring>   </event>  </componentinfo>  <controllerinfo>   <controllername>org.olat.repository.wizard.ui.AccessAndPropertiesController</controllername>   <controllername>org.olat.core.gui.control.generic.wizard.StepsMainRunController</controllername>   <controllername>org.olat.course.editor.EditorMainController</controllername>   <controllername>org.olat.course.run.CourseRuntimeController</controllername>   <controllername>org.olat.core.commons.fullWebApp.BaseFullWebappController</controllername>  </controllerinfo> </dispatchinfo> ::_:: java.lang.NullPointerException: Cannot read field "scale" because "multiplicand" is null
at java.base/java.math.BigDecimal.multiply(BigDecimal.java:1572)
at org.olat.course.run.scoring.ScoreScalingHelper.getWeightedScore(ScoreScalingHelper.java:135)
at org.olat.course.run.scoring.ScoreScalingHelper.getWeightedFloatScore(ScoreScalingHelper.java:139)
at org.olat.course.nodes.CheckListCourseNode.updateScorePassedOnPublish(CheckListCourseNode.java:772)
at org.olat.course.nodes.CheckListCourseNode.updateOnPublish(CheckListCourseNode.java:729)
at org.olat.course.editor.PublishProcess.applyPublishSet(PublishProcess.java:494)
at org.olat.course.editor.EditorMainController$3.execute(EditorMainController.java:1332)
at org.olat.core.gui.control.generic.wizard.StepsMainRunController.finishWizard(StepsMainRunController.java:435)
at org.olat.core.gui.control.generic.wizard.StepsMainRunController.event(StepsMainRunController.java:417)
at org.olat.core.gui.control.DefaultController$1.run(DefaultController.java:262)
at org.olat.core.logging.activity.ThreadLocalUserActivityLoggerInstaller.runWithUserActivityLogger(ThreadLocalUserActivityLoggerInstaller.java:108)
at org.olat.core.gui.control.DefaultController.dispatchEvent(DefaultController.java:258)
at org.olat.core.gui.control.DefaultController.fireEvent(DefaultController.java:203)
at org.olat.repository.wizard.ui.AccessAndPropertiesController.formOK(AccessAndPropertiesController.java:142)
at org.olat.core.gui.components.form.flexible.impl.FormBasicController.formFinish(FormBasicController.java:334)
at org.olat.core.gui.control.generic.wizard.StepFormBasicController.event(StepFormBasicController.java:143)
at org.olat.core.gui.control.DefaultController.dispatchEvent(DefaultController.java:216)
at org.olat.core.gui.components.AbstractComponent.lambda$fireEvent$0(AbstractComponent.java:262)
at org.olat.core.logging.activity.ThreadLocalUserActivityLoggerInstaller.runWithUserActivityLogger(ThreadLocalUserActivityLoggerInstaller.java:108)
at org.olat.core.gui.components.AbstractComponent.fireEvent(AbstractComponent.java:262)
at org.olat.core.gui.components.form.flexible.impl.FormWrapperContainer.fireValidation(FormWrapperContainer.java:129)
at org.olat.core.gui.components.form.flexible.impl.Form.submit(Form.java:462)
at org.olat.core.gui.components.form.flexible.impl.Form.submitAndFinish(Form.java:457)
at org.olat.core.gui.control.generic.wizard.StepsMainRunController.formInnerEvent(StepsMainRunController.java:225)
at org.olat.core.gui.components.form.flexible.impl.FormBasicController.event(FormBasicController.java:439)
at org.olat.core.gui.control.DefaultController.dispatchEvent(DefaultController.java:216)
at org.olat.core.gui.components.AbstractComponent.lambda$fireEvent$0(AbstractComponent.java:262)
at org.olat.core.logging.activity.ThreadLocalUserActivityLoggerInstaller.runWithUserActivityLogger(ThreadLocalUserActivityLoggerInstaller.java:108)
at org.olat.core.gui.components.AbstractComponent.fireEvent(AbstractComponent.java:262)
at org.olat.core.gui.components.form.flexible.impl.FormWrapperContainer.fireFormEvent(FormWrapperContainer.java:141)
at org.olat.core.gui.components.form.flexible.impl.Form.fireFormEvent(Form.java:729)
at org.olat.core.gui.components.form.flexible.impl.elements.FormLinkImpl.dispatchFormRequest(FormLinkImpl.java:190)
at org.olat.core.gui.components.form.flexible.impl.FormItemImpl.doDispatchFormRequest(FormItemImpl.java:516)
at org.olat.core.gui.components.form.flexible.impl.Form.evalFormRequest(Form.java:315)
at org.olat.core.gui.components.form.flexible.impl.FormWrapperContainer.doDispatchRequest(FormWrapperContainer.java:110)
at org.olat.core.gui.components.AbstractComponent.dispatchRequest(AbstractComponent.java:220)
at org.olat.core.gui.components.Window.doDispatchToComponent(Window.java:1284)
at org.olat.core.gui.components.Window.dispatchRequest(Window.java:454)
at org.olat.core.gui.components.Window.doDispatchRequest(Window.java:330)
at org.olat.core.gui.components.AbstractComponent.dispatchRequest(AbstractComponent.java:220)
at org.olat.dispatcher.AuthenticatedDispatcher.processValidDispatchURI(AuthenticatedDispatcher.java:289)
at org.olat.dispatcher.AuthenticatedDispatcher.execute(AuthenticatedDispatcher.java:194)
at org.olat.core.servlets.OpenOLATServlet.executeUserRequest(OpenOLATServlet.java:307)
at org.olat.core.servlets.OpenOLATServlet.doPost(OpenOLATServlet.java:235)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
at org.olat.core.servlets.OpenOLATServlet.service(OpenOLATServlet.java:167)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.olat.core.servlets.HeadersFilter.doFilter(HeadersFilter.java:64)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:431)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1683)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1243)
at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:632)
at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:608)
at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:840)
```
when publishing automatically:
```
2024-03-08 14:07:09.365 [ajp-nio2-127.0.0.1-8009-exec-5] ERROR  QuickPublishController ^%^ I42222-J76895 ^%^ org.olat.course.editor.QuickPublishController ^%^ 5334106112 ^%^ 127.0.0.1 ^%^ https://localhost/auth/RepositoryEntry/5334466563/Editor/0 ^%^ Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0 ^%^ java.lang.NullPointerException: Cannot read field "scale" because "multiplicand" is null
at java.base/java.math.BigDecimal.multiply(BigDecimal.java:1572)
at org.olat.course.run.scoring.ScoreScalingHelper.getWeightedScore(ScoreScalingHelper.java:135)
at org.olat.course.run.scoring.ScoreScalingHelper.getWeightedFloatScore(ScoreScalingHelper.java:139)
at org.olat.course.nodes.CheckListCourseNode.updateScorePassedOnPublish(CheckListCourseNode.java:772)
at org.olat.course.nodes.CheckListCourseNode.updateOnPublish(CheckListCourseNode.java:729)
at org.olat.course.editor.PublishProcess.applyPublishSet(PublishProcess.java:494)
at org.olat.course.editor.QuickPublishController.doAutoPublish(QuickPublishController.java:157)
at org.olat.course.editor.QuickPublishController.event(QuickPublishController.java:108)
at org.olat.core.gui.control.DefaultController.dispatchEvent(DefaultController.java:216)
at org.olat.core.gui.components.AbstractComponent.lambda$fireEvent$0(AbstractComponent.java:262)
at org.olat.core.logging.activity.ThreadLocalUserActivityLoggerInstaller.runWithUserActivityLogger(ThreadLocalUserActivityLoggerInstaller.java:108)
at org.olat.core.gui.components.AbstractComponent.fireEvent(AbstractComponent.java:262)
at org.olat.core.gui.components.link.Link.dispatch(Link.java:214)
at org.olat.core.gui.components.link.Link.doDispatchRequest(Link.java:201)
at org.olat.core.gui.components.AbstractComponent.dispatchRequest(AbstractComponent.java:220)
at org.olat.core.gui.components.Window.doDispatchToComponent(Window.java:1284)
at org.olat.core.gui.components.Window.dispatchRequest(Window.java:454)
at org.olat.core.gui.components.Window.doDispatchRequest(Window.java:330)
at org.olat.core.gui.components.AbstractComponent.dispatchRequest(AbstractComponent.java:220)
at org.olat.dispatcher.AuthenticatedDispatcher.processValidDispatchURI(AuthenticatedDispatcher.java:289)
at org.olat.dispatcher.AuthenticatedDispatcher.execute(AuthenticatedDispatcher.java:194)
at org.olat.core.servlets.OpenOLATServlet.executeUserRequest(OpenOLATServlet.java:307)
at org.olat.core.servlets.OpenOLATServlet.doPost(OpenOLATServlet.java:235)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
at org.olat.core.servlets.OpenOLATServlet.service(OpenOLATServlet.java:167)
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.olat.core.servlets.HeadersFilter.doFilter(HeadersFilter.java:64)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:431)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1683)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1243)
at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:632)
at org.apache.tomcat.util.net.Nio2Endpoint$Nio2SocketWrapper$2.completed(Nio2Endpoint.java:608)
at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by lainsr** [comment]
Hi,

I have opened an issue: https://track.frentix.com/issue/OO-7658/RS-update-a-check-list

Thank you for reporting
Best regards
