### ISSUE TITLE
getting null pointer exception when clicking on subject tab

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#28]
When clicking on the Question bank there is one administration link on the left side on click subject link inside we are getting null pointer exception seems taxonomy value is null
<img width="1460" alt="Screenshot 2019-08-07 at 6 29 46 PM" src="https://user-images.githubusercontent.com/5021230/62625943-e0faf000-b943-11e9-8ef6-22060dae5155.png">

**Comment by uhensler** [comment]
Please provide the full stack trace.

**Comment by rageshpillai** [comment]
Please find the full stack trace
Hibernate: select resourcere0_.reservation_id as reservation_id1_8_, resourcere0_.creationdate as creationdate2_8_, resourcere0_.expirationdate as expirationdate3_8_, resourcere0_.fk_identity as fk_identity7_8_, resourcere0_.lastmodified as lastmodified4_8_, resourcere0_.fk_resource as fk_resource8_8_, resourcere0_.reservationtype as reservationtype5_8_, resourcere0_.version as version6_8_ from o_ac_reservation resourcere0_ where (resourcere0_.expirationdate is null) and resourcere0_.creationdate<? or resourcere0_.expirationdate<?
12:01:31.952 [http-nio-8080-exec-2] WARN  org.olat.core.gui.exception.ExceptionWindowController - ExceptionWindowController<init>: Throwable occurred, logging the full stacktrace:
java.lang.NullPointerException: null
	at org.olat.modules.taxonomy.manager.TaxonomyLevelTypeDAO.loadTaxonomyLevelTypeByTaxonomy(TaxonomyLevelTypeDAO.java:110) ~[classes/:?]
	at org.olat.modules.taxonomy.manager.TaxonomyServiceImpl.getTaxonomyLevelTypes(TaxonomyServiceImpl.java:284) ~[classes/:?]
	at org.olat.modules.taxonomy.ui.TaxonomyTreeTableController.getFilters(TaxonomyTreeTableController.java:160) ~[classes/:?]
	at org.olat.modules.taxonomy.ui.TaxonomyTreeTableController.initForm(TaxonomyTreeTableController.java:154) ~[classes/:?]
	at org.olat.core.gui.components.form.flexible.impl.FormBasicController.initForm(FormBasicController.java:278) ~[classes/:?]
	at org.olat.modules.taxonomy.ui.TaxonomyTreeTableController.<init>(TaxonomyTreeTableController.java:108) ~[classes/:?]
	at org.olat.modules.qpool.ui.admin.TaxonomyAdminController.<init>(TaxonomyAdminController.java:55) ~[classes/:?]
	at org.olat.modules.qpool.ui.tree.TaxonomyAdminTreeNode.getController(TaxonomyAdminTreeNode.java:55) ~[classes/:?]
	at org.olat.modules.qpool.ui.QuestionPoolMainEditorController.doSelectQuestionsNode(QuestionPoolMainEditorController.java:380) ~[classes/:?]
	at org.olat.modules.qpool.ui.QuestionPoolMainEditorController.doSelectControllerTreeNode(QuestionPoolMainEditorController.java:155) ~[classes/:?]
	at org.olat.modules.qpool.ui.QuestionPoolMainEditorController.event(QuestionPoolMainEditorController.java:144) ~[classes/:?]
	at org.olat.core.gui.control.DefaultController.dispatchEvent(DefaultController.java:206) ~[classes/:?]
	at org.olat.core.gui.components.AbstractComponent$1.run(AbstractComponent.java:240) ~[classes/:?]
	at org.olat.core.logging.activity.ThreadLocalUserActivityLoggerInstaller.runWithUserActivityLogger(ThreadLocalUserActivityLoggerInstaller.java:108) ~[classes/:?]
	at org.olat.core.gui.components.AbstractComponent.fireEvent(AbstractComponent.java:238) ~[classes/:?]
	at org.olat.core.gui.components.tree.MenuTree.handleClick(MenuTree.java:297) ~[classes/:?]
	at org.olat.core.gui.components.tree.MenuTree.doDispatchRequest(MenuTree.java:196) ~[classes/:?]
	at org.olat.core.gui.components.AbstractComponent.dispatchRequest(AbstractComponent.java:193) ~[classes/:?]
	at org.olat.core.gui.components.Window.doDispatchToComponent(Window.java:1202) ~[classes/:?]
	at org.olat.core.gui.components.Window.dispatchRequest(Window.java:398) [classes/:?]
	at org.olat.core.gui.components.Window.doDispatchRequest(Window.java:282) [classes/:?]
	at org.olat.core.gui.components.AbstractComponent.dispatchRequest(AbstractComponent.java:193) [classes/:?]
	at org.olat.dispatcher.AuthenticatedDispatcher.processValidDispatchURI(AuthenticatedDispatcher.java:263) [classes/:?]
	at org.olat.dispatcher.AuthenticatedDispatcher.execute(AuthenticatedDispatcher.java:184) [classes/:?]
	at org.olat.core.servlets.OpenOLATServlet.executeUserRequest(OpenOLATServlet.java:269) [classes/:?]
	at org.olat.core.servlets.OpenOLATServlet.doPost(OpenOLATServlet.java:216) [classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
	at org.olat.core.servlets.OpenOLATServlet.service(OpenOLATServlet.java:160) [classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.42]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.42]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.42]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.42]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.42]
	at org.olat.core.servlets.HeadersFilter.doFilter(HeadersFilter.java:95) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.42]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.42]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.42]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.42]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.42]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) [catalina.jar:8.5.42]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.42]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) [catalina.jar:8.5.42]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.42]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.42]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) [tomcat-coyote.jar:8.5.42]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.42]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) [tomcat-coyote.jar:8.5.42]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.42]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.42]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.42]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
12:01:31.953 [http-nio-8080-exec-2] ERROR org.olat.core.logging.OLATRuntimeException - **RedScreen** null ::_::<dispatchinfo>  <componentinfo>   <compname>qpoolTree</compname>   <compclass>org.olat.core.gui.components.tree.MenuTree</compclass>   <extendedinfo>n/a</extendedinfo>   <event>    <class>org.olat.core.gui.components.tree.TreeEvent</class>    <command>ctncl</command>    <tostring>TreeEvent:{cmd:ctncl, nodeid:100175722673200}</tostring>   </event>  </componentinfo>  <controllerinfo>   <controllername>org.olat.modules.qpool.ui.QuestionPoolMainEditorController</controllername>   <controllername>org.olat.core.commons.fullWebApp.BaseFullWebappController</controllername>  </controllerinfo> </dispatchinfo> ::_::
org.olat.core.logging.OLATRuntimeException: null
	at org.olat.core.gui.exception.ExceptionWindowController.<init>(ExceptionWindowController.java:116) [classes/:?]
	at org.olat.core.gui.exception.MsgFactory.createMessageChiefController(MsgFactory.java:57) [classes/:?]
	at org.olat.core.gui.exception.MsgFactory.createMessageChiefController(MsgFactory.java:46) [classes/:?]
	at org.olat.core.gui.components.Window.dispatchRequest(Window.java:586) [classes/:?]
	at org.olat.core.gui.components.Window.doDispatchRequest(Window.java:282) [classes/:?]
	at org.olat.core.gui.components.AbstractComponent.dispatchRequest(AbstractComponent.java:193) [classes/:?]
	at org.olat.dispatcher.AuthenticatedDispatcher.processValidDispatchURI(AuthenticatedDispatcher.java:263) [classes/:?]
	at org.olat.dispatcher.AuthenticatedDispatcher.execute(AuthenticatedDispatcher.java:184) [classes/:?]
	at org.olat.core.servlets.OpenOLATServlet.executeUserRequest(OpenOLATServlet.java:269) [classes/:?]
	at org.olat.core.servlets.OpenOLATServlet.doPost(OpenOLATServlet.java:216) [classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [servlet-api.jar:?]
	at org.olat.core.servlets.OpenOLATServlet.service(OpenOLATServlet.java:160) [classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.42]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.42]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.42]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.42]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.42]
	at org.olat.core.servlets.HeadersFilter.doFilter(HeadersFilter.java:95) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.42]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.42]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.42]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.42]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.42]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) [catalina.jar:8.5.42]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.42]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) [catalina.jar:8.5.42]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.42]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.42]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) [tomcat-coyote.jar:8.5.42]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.42]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) [tomcat-coyote.jar:8.5.42]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.42]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.42]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.42]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
	at org.olat.modules.taxonomy.manager.TaxonomyLevelTypeDAO.loadTaxonomyLevelTypeByTaxonomy(TaxonomyLevelTypeDAO.java:110) ~[classes/:?]
	at org.olat.modules.taxonomy.manager.TaxonomyServiceImpl.getTaxonomyLevelTypes(TaxonomyServiceImpl.java:284) ~[classes/:?]
	at org.olat.modules.taxonomy.ui.TaxonomyTreeTableController.getFilters(TaxonomyTreeTableController.java:160) ~[classes/:?]
	at org.olat.modules.taxonomy.ui.TaxonomyTreeTableController.initForm(TaxonomyTreeTableController.java:154) ~[classes/:?]
	at org.olat.core.gui.components.form.flexible.impl.FormBasicController.initForm(FormBasicController.java:278) ~[classes/:?]
	at org.olat.modules.taxonomy.ui.TaxonomyTreeTableController.<init>(TaxonomyTreeTableController.java:108) ~[classes/:?]
	at org.olat.modules.qpool.ui.admin.TaxonomyAdminController.<init>(TaxonomyAdminController.java:55) ~[classes/:?]
	at org.olat.modules.qpool.ui.tree.TaxonomyAdminTreeNode.getController(TaxonomyAdminTreeNode.java:55) ~[classes/:?]
	at org.olat.modules.qpool.ui.QuestionPoolMainEditorController.doSelectQuestionsNode(QuestionPoolMainEditorController.java:380) ~[classes/:?]
	at org.olat.modules.qpool.ui.QuestionPoolMainEditorController.doSelectControllerTreeNode(QuestionPoolMainEditorController.java:155) ~[classes/:?]
	at org.olat.modules.qpool.ui.QuestionPoolMainEditorController.event(QuestionPoolMainEditorController.java:144) ~[classes/:?]
	at org.olat.core.gui.control.DefaultController.dispatchEvent(DefaultController.java:206) ~[classes/:?]
	at org.olat.core.gui.components.AbstractComponent$1.run(AbstractComponent.java:240) ~[classes/:?]
	at org.olat.core.logging.activity.ThreadLocalUserActivityLoggerInstaller.runWithUserActivityLogger(ThreadLocalUserActivityLoggerInstaller.java:108) ~[classes/:?]
	at org.olat.core.gui.components.AbstractComponent.fireEvent(AbstractComponent.java:238) ~[classes/:?]
	at org.olat.core.gui.components.tree.MenuTree.handleClick(MenuTree.java:297) ~[classes/:?]
	at org.olat.core.gui.components.tree.MenuTree.doDispatchRequest(MenuTree.java:196) ~[classes/:?]
	at org.olat.core.gui.components.AbstractComponent.dispatchRequest(AbstractComponent.java:193) ~[classes/:?]
	at org.olat.core.gui.components.Window.doDispatchToComponent(Window.java:1202) ~[classes/:?]
	at org.olat.core.gui.components.Window.dispatchRequest(Window.java:398) ~[classes/:?]
	... 34 more

**Comment by rageshpillai** [comment]
we already created taxonomy but its not reflect in question bank admin. and for the taxonomy external id is not getting generated
<img width="1197" alt="Screenshot 2019-08-08 at 5 54 19 PM" src="https://user-images.githubusercontent.com/5021230/62703046-e6207380-ba05-11e9-9908-80aeafd1bb14.png">

**Comment by lainsr** [comment]
You need to choose a taxonomy in the field "Taxonomy". You don't have one in your screenshot. To create a taxonomy, go in Administration > Modules > Taxonomy, create a new taxonomy. Open the taxonomy and in tab "Taxonomy", create at least one "Taxonomy level".

**Comment by lainsr** [comment]
It's possible that the configured taxonomy doesn't exists anymore in the database. I try to explain, in the screenshot, you see configuration saved in the file system. In this configuration you have the primary key of the taxonomy saved in the database. If you delete your database for example and recreate it, you have an issue with your configuration.
A quick solution is to stop OpenOlat, go to the file system in your "userdata.dir" /system/configuration and delete the file named "org.olat.modules.qpool.QuestionPoolModule.properties" and restart OpenOlat. On start, it will recreate a default taxonomy for the question pool.
It's very important that your file system stay in sync with your database, not only for configuration but for all resources like courses or tests.
