### ISSUE TITLE
content path of tomcat for Openolat

### ISSUE THREAD

**Issue by punit-porwal** [OpenOLAT/OpenOLAT#82]
Hi Team,

I have deployed openolat-lms-15.5-SNAPSHOT.war in external tomcat and set require VM parameter into ~bin/setenv.sh file
but once we start the tomcat server then not able to fetch result from below URL

http://localhost:8088/openolat
or http://localhost:8088
Getting 404 error from tomcat

but I have hit below URL then start working
http://localhost:8080/openolat-lms-15.5-SNAPSHOT/

Is there any property we are missing if yes please suggest 

One more issue getting after deployment , please suggest if any things have to add.

19:21:32.164 [main] ERROR org.olat.core.util.WebappHelper - Path to source wrong, debugging may not work as expected: 
java.lang.Exception: getSourcePath
        at org.olat.core.util.WebappHelper.getSourcePath(WebappHelper.java:242) ~[classes/:15.5-SNAPSHOT]
        at org.olat.core.gui.render.velocity.VelocityHelper.init(VelocityHelper.java:88) ~[classes/:15.5-SNAPSHOT]
        at org.olat.core.gui.render.velocity.VelocityHelper.<init>(VelocityHelper.java:65) ~[classes/:15.5-SNAPSHOT]
        at org.olat.core.gui.render.velocity.VelocityHelper.<clinit>(VelocityHelper.java:54) ~[classes/:15.5-SNAPSHOT]
        at org.olat.core.gui.render.velocity.VelocityModule.init(VelocityModule.java:65) ~[classes/:15.5-SNAPSHOT]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
   

Thanks
Punit Porwal

**Comment by lainsr** [comment]
Hi Punit

The /openolat-lms-15.5-SNAPSHOT/ is the name of your WAR file. If you want to use http://localhost:8088/, rename the WAR file ROOT.war or configured Tomcat.

15.5 is currently in development. If we change the database schema, you need to apply the changes manually and perhaps run again the upgraders. I would strongly suggest to work with 15.4

The source path is this property: project.build.home.directory, it's used for development and translation server. You don't want it on a production server. For translations, we run a community translation server, we take care of the merging stuff and the translations are incorporated in the standard release.

**Comment by punit-porwal** [comment]
Thanks lainsr for your detail, closing this
